"""create applications table

Revision ID: 4fbc1b26cb64
Revises: 277147cb6c84
Create Date: 2026-08-30 19:49:29.211831

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fbc1b26cb64"
down_revision: str | Sequence[str] | None = "277147cb6c84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "saved",
                "applied",
                "screening",
                "interview",
                "technical_interview",
                "final_interview",
                "offer",
                "accepted",
                "rejected",
                "withdrawn",
                name="application_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="saved",
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "linkedin",
                "indeed",
                "company_website",
                "recruiter",
                "referral",
                "other",
                name="job_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "work_model",
            sa.Enum(
                "onsite",
                "hybrid",
                "remote",
                name="work_model",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("job_url", sa.String(length=2048), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_company_id"), "applications", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_company_id"), table_name="applications")
    op.drop_table("applications")
    # ### end Alembic commands ###
