"""create application events table

Revision ID: dff581848917
Revises: 4fbc1b26cb64
Create Date: 2026-08-30 20:41:37.136018

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dff581848917"
down_revision: str | Sequence[str] | None = "4fbc1b26cb64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_events",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "created",
                "status_changed",
                "interview_scheduled",
                "interview_completed",
                "offer_received",
                "note_added",
                name="application_event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "from_status",
            sa.Enum(
                "saved",
                "applied",
                "screening",
                "interview",
                "technical_interview",
                "final_interview",
                "offer",
                "accepted",
                "rejected",
                "withdrawn",
                name="application_status",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "saved",
                "applied",
                "screening",
                "interview",
                "technical_interview",
                "final_interview",
                "offer",
                "accepted",
                "rejected",
                "withdrawn",
                name="application_status",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('created', 'status_changed', 'interview_scheduled', 'interview_completed', 'offer_received', 'note_added')",
            name="application_event_type",
        ),
        sa.CheckConstraint(
            "from_status IN ('saved', 'applied', 'screening', 'interview', 'technical_interview', 'final_interview', 'offer', 'accepted', 'rejected', 'withdrawn')",
            name="application_event_from_status",
        ),
        sa.CheckConstraint(
            "to_status IN ('saved', 'applied', 'screening', 'interview', 'technical_interview', 'final_interview', 'offer', 'accepted', 'rejected', 'withdrawn')",
            name="application_event_to_status",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_events_application_id"),
        "application_events",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_application_events_application_id"), table_name="application_events"
    )
    op.drop_table("application_events")
    # ### end Alembic commands ###
